# For non-given arguments, just leave it empty
model:
  name: BalancedGRUAdvPONI
  loss_config:
    type:
train_config:
  data_meta_info:
    # variable nicknames are listed in LoaderMapping
    rain:
      path: "/work/dong1128/database/rain_rate_ten_min"
      formatter: "%Y%m%d_%H%M.nc"
      normalize_factor:
      is_inp: True
      is_oup: True
    radar:
      path: "/work/dong1128/database/radar_2d_cropped"
      formatter: "%Y%m%d_%H%M.nc"
      normalize_factor: 30
      is_inp: True
      is_oup: False
  data_loader_params:
    # all the keys are listed in the constructor of PLDataLoader
    start_date: 2021_06_04 
    end_date: 2021_12_31
    ratios: [0.6, 0.2, 0.2]
    batch_size: 32
    num_workers: 4
    input_len: 6
    output_len: 3
    output_interval: 6
    img_size: (120, 120)
    sampling_rate: 6
    # testing data in constant
    # crop region in constant