# For non-given arguments, just leave it empty
model:
  name: HELLO
  loss_config:
    type:
train_config:
  data_meta_info:
    rain:
      path: "/work/dong1128/database/rain_rate_ten_min"
      formatter: "%Y%m%d_%H%M.nc"
      normalize_factor:
      is_inp: True
      is_oup: True
    radar:
      path: "/work/dong1128/database/radar_2d_cropped"
      formatter: "%Y%m%d_%H%M.nc"
      normalize_factor: 30
      is_inp: True
      is_oup: False
  data_loader_params:
    # all the keys are listed in the constructor of PLDataLoader
    train_start: 2021_06_04 
    train_end: 2021_12_31
    val_start: 2022_01_01
    val_end: 2022_06_01
    batch_size: 32
    num_workers: 4
    input_len: 6
    output_len: 3
    output_interval: 6
    img_size: (120, 120)
    sampling_rate: 6