# For non-given arguments, just leave it empty
model:
  model_config:
    name: BalancedGRUAdvPONI
    add_hetr_from_poni: False
    teach_forcing_ratio: 0.5
    discriminator_downsample: 5
  loss_config:
    type: WeightedMAE
    balance_weight: [1, 2, 5, 10, 30]
    balance_threshold: 0.5
    adversarial_weight: 0.01
    learning_rate: 0.0001
  checkpoint_dir: "/wk171/handsomedong/deepQPF_research/checkpoint/"
train_config:
  data_meta_info:
    # variable nicknames are listed in LoaderMapping
    rain:
      path: "/bk2/handsomedong/deepQPF_DB/rain_rate_ten_min_jay"
      formatter: "%Y%m%d_%H%M.jay"
      normalize_factor: 10
      is_inp: True
      is_oup: True
    radar:
      path: "/bk2/handsomedong/deepQPF_DB/radar_2d_cropped_jay"
      formatter: "%Y%m%d_%H%M.jay"
      normalize_factor: 35
      is_inp: True
      is_oup: False
  data_loader_params:
    # all the keys are listed in the constructor of PLDataLoader
    start_date: 2015_01_01_00_00
    end_date: 2015_12_31_23_50
    order_by_time: True
    ratios: [3, 1, 1] # order: train/valid/evalu
    input_len: 6
    output_len: 3
    output_interval: 6
    target_lat: [20.125, 26.8625]
    target_lon: [118.125, 123.3625]
    target_shape: (540, 420)
    sampling_rate: 3
    batch_size: 8
    num_workers: 4