model:
  model_config:
    name: Transformer
  loss_config:
    type: WeightedMAE
    balance_weight: [1, 2, 5, 10, 30]
    balance_threshold: 0.5
  checkpoint_dir: "/home/dong1128/deepQPF_research/checkpoint/"
train_config:
  data_meta_info:
    # variable nicknames are listed in LoaderMapping
    rain:
      path: "/work/dong1128/database/rain_rate_ten_min_jay"
      formatter: "%Y%m%d_%H%M.jay"
      normalize_factor: 10
      is_inp: True
      is_oup: True
    radar:
      path: "/work/dong1128/database/radar_2d_cropped_jay"
      formatter: "%Y%m%d_%H%M.jay"
      normalize_factor: 35
      is_inp: True
      is_oup: False
  data_loader_params:
    # all the keys are listed in the constructor of PLDataLoader
    start_date: 2015_01_01_00_00
    end_date: 2021_12_31_23_50
    order_by_time: True
    ratios: [0.6, 0.2, 0.2] # order: train/valid/evalu
    input_len: 6
    output_len: 3
    output_interval: 6
    target_lat: [20.125, 26.8625]
    target_lon: [118.125, 123.3625]
    target_shape: (54, 42)
    sampling_rate: 5
    batch_size: 64
    num_workers: 4